### ISSUE TITLE
Gradle project with Spring Boot 3.0.0-RC2, Cloud Stream, and Spring for Apache Kafka Streams fails to run tests

### ISSUE THREAD

**Issue by edysli** [spring-io/start.spring.io#1036]
I generated a project based on Spring Boot 3.0.0-RC2 and Java 17, selecting "Cloud Stream", and "Spring for Apache Kafka Streams" as dependencies (as recommended in the [Spring Cloud Stream reference documentation for Apache Kafka Streams binder](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_usage_2)), but the build fails when running tests.

> A quick way to bootstrap a new project for Kafka Streams binder is to use [Spring Initializr](https://start.spring.io/) and then select "Cloud Streams" and "Spring for Kafka Streams" [...]

The generated `build.gradle` file is
```groovy
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.0.0-RC2'
	id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
}

ext {
	set('springCloudVersion', "2022.0.0-RC1")
}

dependencies {
	implementation 'org.apache.kafka:kafka-streams'
	implementation 'org.springframework.cloud:spring-cloud-stream'
	implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
```

Running `gradle build --debug` fails with:
```
2022-11-22T10:12:30.389+0100 [DEBUG] [TestEventLogger] Gradle Test Executor 26 STARTED
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger] Gradle Test Executor 26 FAILED
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]     org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 26.
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         Caused by:
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]         java.lang.NoClassDefFoundError: org/junit/platform/launcher/TestExecutionListener
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/java.lang.ClassLoader.defineClass1(Native Method)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/java.lang.Class.forName0(Native Method)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/java.lang.Class.forName(Class.java:467)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
2022-11-22T10:12:30.421+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at org.junit.platform.launcher.core.LauncherFactory.registerTestExecutionListeners(LauncherFactory.java:179)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at org.junit.platform.launcher.core.LauncherFactory.createDefaultLauncher(LauncherFactory.java:137)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:109)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:97)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             ... 18 more
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             Caused by:
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]             java.lang.ClassNotFoundException: org.junit.platform.launcher.TestExecutionListener
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]                 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]                 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]                 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2022-11-22T10:12:30.422+0100 [DEBUG] [TestEventLogger]                 ... 50 more
```

The only way I've found to make the build succeed is to comment out the line `implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'` and this changes how JUnit 5 is pulled into transitive dependencies (run `gradle dependencies` to see this), so there may be something here... Adding `testImplementation 'org.junit.jupiter:junit-jupiter'` doesn't help.

Gradle and Java versions:
```
$ gradle --version

------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Eclipse Adoptium 17.0.5+8)
OS:           Mac OS X 12.6.1 aarch64
```

**Comment by wilkinsona** [comment]
The problem does not occur with Spring Cloud 2022.0.0-RC2. start.spring.io will use that version in due course – the Cloud team have not yet asked us to upgrade.

**Comment by snicoll** [comment]
@edysli it should also be noted that there's nothing we can do about it here. As you've figured out yourself, the problem comes from adding Spring Cloud Stream so the issue should have been reported there. I am looking at upgrading to RC2 asap.

**Comment by edysli** [comment]
Thank you for your answers @wilkinsona and @snicoll. Using Spring Cloud 2022.0.0-RC2 fixes it indeed.

It would be a large number of combinations to test, but nonetheless nice if start.spring.io didn't offer such "invalid" projects for download.
