### ISSUE TITLE
PicoCLI annotation processor not working in Kotlin/GraalVM projects

### ISSUE THREAD

**Issue by thombergs** [spring-io/start.spring.io#1076]
When I create a project with Kotlin, PicoCLI and GraalVM, PicoCLI's annotation processor isn't working. This [annotation processor](https://picocli.info/picocli-on-graalvm.html) is responsible for creating the runtime hints for GraalVM. The effect is that when I run the native executable that is the result of `./gradlew nativeCompile`, I get this error:

```
2022-12-25T07:12:09.568+11:00 ERROR 62436 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770) ~[demo:3.0.1]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:751) ~[demo:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[demo:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[demo:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[demo:3.0.1]
        at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:13) ~[demo:na]
Caused by: picocli.CommandLine$InitializationException: picocli.CommandLine$AutoHelpMixin@1d0da99b is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations
        at picocli.CommandLine$Model$CommandReflection.validateCommandSpec(CommandLine.java:11985) ~[na:na]
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11815) ~[na:na]
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6388) ~[demo:4.7.0]
        at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:7382) ~[demo:4.7.0]
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11810) ~[na:na]
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6388) ~[demo:4.7.0]
        at picocli.CommandLine.<init>(CommandLine.java:230) ~[demo:4.7.0]
        at picocli.CommandLine.toCommandLine(CommandLine.java:3631) ~[demo:4.7.0]
        at picocli.CommandLine.access$16600(CommandLine.java:148) ~[demo:4.7.0]
        at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:11840) ~[na:na]
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11806) ~[na:na]
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6388) ~[demo:4.7.0]
        at picocli.CommandLine.<init>(CommandLine.java:230) ~[demo:4.7.0]
        at picocli.CommandLine.<init>(CommandLine.java:224) ~[demo:4.7.0]
        at com.example.demo.PicoCliRunner.run(PicoCliRunner.kt:17) ~[demo:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767) ~[demo:3.0.1]
        ... 5 common frames omitted
```

I don't know whether this is a general problem with annotation processing in Kotlin projects or if this is related to PicoCLI but I assume it's the former.

Here are reproducer projects:
- [reproducer project with Kotlin and Gradle](https://github.com/thombergs/kotlin-picocli-native) (not working)
- [same project with Kotlin and Maven](https://github.com/thombergs/picocli-kotlin-native-maven) (not working)
- [same project with Java and Gradle](https://github.com/thombergs/java-picocli-native) (working)

To avoid having to add the runtime hints manually, I configured [kapt](https://kotlinlang.org/docs/kapt.html) to activate the annotation processor:

```groovy
plugins {
    id 'org.jetbrains.kotlin.kapt' version '1.7.21'
}

dependencies {
    kapt 'info.picocli:picocli-codegen:4.7.0'
}

kapt {
    arguments {
        arg("project", "${project.group}/${project.name}")
    }
}
```

Note that kapt is in maintenance mode and superseded by [KSP](https://kotlinlang.org/docs/ksp-overview.html). I didn't take the time to look into KSP, though, as I didn't find good docs when I looked.

Kotlin/GraalVM projects generated by Initializt that need annotation processing should probably configure KSP/kapt to work properly?

**Comment by wilkinsona** [comment]
Relates to https://github.com/spring-io/start.spring.io/issues/1060.

**Comment by bclozel** [comment]
I've just discussed that with @sdeleuze and it seems that:

* Picocli declined for now KSP support, see remkop/picocli#1564 - so we should probably go with kapt. [The list of supported libraries](https://kotlinlang.org/docs/ksp-overview.html#supported-libraries) does not show anything we're interested in so far I think.
* it sounds like we need spring-io/initializr#438 - in the meantime, we now have a `Dependency.ANNOTATION_PROCESSOR` scope, so I guess some comments there are outdated

**Comment by yogeshVU** [comment]
@bclozel what is the interim solution for this? how does one configure the KAPT plugin as suggested?

**Comment by bclozel** [comment]
@yogeshVU I think the Picocli docs cover this: https://picocli.info/#_enabling_the_annotation_processor

**Comment by mhalbritter** [comment]
As the PicoCLI Spring Boot starter [doesn't support Boot 3.2.x or 3.3.x](https://github.com/remkop/picocli/blob/main/picocli-spring-boot-starter/README.md), we have removed it from the site. This issue is obsolete now.
