### ISSUE TITLE
Configure org.hibernate.orm plugin for Gradle builds using the Kotlin DSL

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#1229]
It looks like https://hibernate.atlassian.net/browse/HHH-15707 has been fixed so we can configure the `org.hibernate.orm` plugin for Kotlin projects now.

When we've confirmed that this works we should update Spring Boot's wiki to remove [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM#hibernate).

**Comment by rkudryashov** [comment]
@wilkinsona I have the same error as in https://github.com/oracle/graalvm-reachability-metadata/issues/324 even after [configuration](https://github.com/rkudryashov/sb-repro/blob/master/sb-repro-1/build.gradle.kts#L55C1-L61C2) of `org.hibernate.orm` Gradle Plugin:

```
sb-repro     | 2023-07-01T08:51:50.000Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
sb-repro     |
sb-repro     | com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.hibernate.query.hql.spi.SqmQueryImplementor, interface org.hibernate.query.sqm.internal.SqmInterpretationsKey$InterpretationsKeySource, interface org.hibernate.query.spi.DomainQueryExecutionContext, 
interface org.hibernate.query.SelectionQuery, interface org.hibernate.query.CommonQueryContract] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
sb-repro     |  at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
sb-repro     |  at com.oracle.svm.core.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:171) ~[na:na]
sb-repro     |  at java.base@17.0.7/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:47) ~[com.romankudryashov.sbrepro.SbReproKt:na]
sb-repro     |  at java.base@17.0.7/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037) ~[com.romankudryashov.sbrepro.SbReproKt:na]
sb-repro     |  at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:316) ~[na:na]
sb-repro     |  at jdk.proxy4/jdk.proxy4.$Proxy52.createQuery(Unknown Source) ~[na:na]
sb-repro     |  at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.createQuery(PartTreeJpaQuery.java:297) ~[com.romankudryashov.sbrepro.SbReproKt:3.1.1]
sb-repro     |  at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.createQuery(PartTreeJpaQuery.java:242) ~[com.romankudryashov.sbrepro.SbReproKt:3.1.1]
sb-repro     |  at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.doCreateQuery(PartTreeJpaQuery.java:113) ~[na:na]
sb-repro     |  at org.springframework.data.jpa.repository.query.AbstractJpaQuery.createQuery(AbstractJpaQuery.java:234) ~[com.romankudryashov.sbrepro.SbReproKt:3.1.1]
sb-repro     |  at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:129) ~[na:na]
sb-repro     |  at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:92) ~[com.romankudryashov.sbrepro.SbReproKt:3.1.1]
sb-repro     |  at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148) ~[com.romankudryashov.sbrepro.SbReproKt:3.1.1]
sb-repro     |  at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136) ~[com.romankudryashov.sbrepro.SbReproKt:3.1.1]
sb-repro     |  at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[com.romankudryashov.sbrepro.SbReproKt:3.1.1]
sb-repro     |  at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[com.romankudryashov.sbrepro.SbReproKt:3.1.1]
sb-repro     |  at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164) ~[na:na]
sb-repro     |  at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[na:na]
sb-repro     |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:72) ~[na:na]
sb-repro     |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[na:na]
sb-repro     |  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[na:na]
sb-repro     |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135) ~[na:na]
sb-repro     |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[na:na]
sb-repro     |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:94) ~[na:na]
sb-repro     |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244) ~[na:na]
sb-repro     |  at jdk.proxy4/jdk.proxy4.$Proxy49.findFirst50ByStatusOrderByCreatedAtAsc(Unknown Source) ~[na:na]
sb-repro     |  at com.romankudryashov.sbrepro.task.InboxProcessingTask.execute(InboxProcessingTask.kt:20) ~[com.romankudryashov.sbrepro.SbReproKt:na]
sb-repro     |  at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568) ~[com.romankudryashov.sbrepro.SbReproKt:na]
sb-repro     |  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[na:na]
sb-repro     |  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[com.romankudryashov.sbrepro.SbReproKt:6.0.10]
sb-repro     |  at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96) ~[na:na]
sb-repro     |  at java.base@17.0.7/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
sb-repro     |  at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[com.romankudryashov.sbrepro.SbReproKt:na]
sb-repro     |  at java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
sb-repro     |  at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[com.romankudryashov.sbrepro.SbReproKt:na]
sb-repro     |  at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
sb-repro     |  at java.base@17.0.7/java.lang.Thread.run(Thread.java:833) ~[com.romankudryashov.sbrepro.SbReproKt:na]
sb-repro     |  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[com.romankudryashov.sbrepro.SbReproKt:na]
sb-repro     |  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203) ~[na:na]
sb-repro     |
```

Could it be caused by something else?
