### ISSUE TITLE
spring-web is not added being a required dependency

### ISSUE THREAD

**Issue by Haarolean** [spring-io/start.spring.io#1338]
Hi,

observed a problem with start.spring.io: 

if you create an epp with security and oauth2 client starters but do not include spring-web dependency explicitly, you'll get the following exception:

<details>
  <summary>Stacktrace</summary>
  
```
2023-11-05T05:09:22.720+08:00 ERROR 54613 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-3.1.1.jar:3.1.1]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:183) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:427) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:287) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:344) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:115) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:771) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:589) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.1.jar:3.1.1]
	at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483) ~[spring-core-6.0.10.jar:6.0.10]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:360) ~[spring-core-6.0.10.jar:6.0.10]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:417) ~[spring-core-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$1(AbstractAutowireCapableBeanFactory.java:748) ~[spring-beans-6.0.10.jar:6.0.10]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:747) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:680) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:651) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1632) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:560) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:532) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:246) ~[spring-boot-autoconfigure-3.1.1.jar:3.1.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:239) ~[spring-boot-autoconfigure-3.1.1.jar:3.1.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:229) ~[spring-boot-autoconfigure-3.1.1.jar:3.1.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:182) ~[spring-boot-autoconfigure-3.1.1.jar:3.1.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:157) ~[spring-boot-autoconfigure-3.1.1.jar:3.1.1]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-3.1.1.jar:3.1.1]
	... 16 common frames omitted
Caused by: java.lang.NoClassDefFoundError: jakarta/servlet/Filter
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.10.jar:6.0.10]
	... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.Filter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
	... 36 common frames omitted

2023-11-05T05:09:22.728+08:00  WARN 54613 --- [           main] o.s.boot.SpringApplication               : Unable to close ApplicationContext

java.lang.IllegalStateException: Failed to introspect Class [org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483) ~[spring-core-6.0.10.jar:6.0.10]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:360) ~[spring-core-6.0.10.jar:6.0.10]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:417) ~[spring-core-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$1(AbstractAutowireCapableBeanFactory.java:748) ~[spring-beans-6.0.10.jar:6.0.10]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:747) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:680) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:651) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1632) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:560) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:532) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:651) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1300) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:867) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:855) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:842) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:782) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.1.jar:3.1.1]
	at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[classes/:na]
Caused by: java.lang.NoClassDefFoundError: jakarta/servlet/Filter
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.10.jar:6.0.10]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.Filter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
	... 25 common frames omitted
  ```
  
</details>

Which can be frustrating for users. I've spent around 15 minutes trying to figure out what's wrong :)

Here's a demo: https://github.com/Haarolean/spring-start-error

**Comment by snicoll** [comment]
@Haarolean thanks for the report but I am not sure what I should do to make it fail the same way as you've described. I ran it untouched and it worked. Then I looked at the pom and removed the web starter. It still works. 

It would be nice if the sample would fail as you've described without any modification.

**Comment by xswapx** [comment]
Can i work on it? or is this issue resolved?

**Comment by bclozel** [comment]
@xswapx There is nothing to do for now. We're waiting for @Haarolean 's feedback.

**Comment by worknet1018** [comment]
[INFO] --- frontend:1.13.4:install-node-and-yarn (install node and yarn) @ start-client ---
[INFO] Node v16.20.0 is already installed.
[INFO] Yarn 1.22.19 is already installed.
[INFO] 
[INFO] --- frontend:1.13.4:yarn (yarn install) @ start-client ---
[INFO] Running 'yarn ' in /opt/start.spring.io/start-client
[INFO] yarn install v1.22.19
[INFO] [1/4] Resolving packages...
[INFO] warning node-sass > make-fetch-happen > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
[INFO] [2/4] Fetching packages...
[INFO] [3/4] Linking dependencies...
[INFO] warning " > react-markdown@8.0.7" has unmet peer dependency "@types/react@>=16".
[INFO] [4/4] Building fresh packages...
[INFO] error /opt/start.spring.io/start-client/node_modules/node-sass: Command failed.
[INFO] Exit code: 1
[INFO] Command: node scripts/install.js
[INFO] Arguments: 
[INFO] Directory: /opt/start.spring.io/start-client/node_modules/node-sass
[INFO] Output:
[INFO] node:internal/modules/cjs/loader:1029
[INFO]   throw err;
[INFO]   ^
[INFO] 
[INFO] Error: Cannot find module '../common/constants'
[INFO] Require stack:
[INFO] 
[INFO] - /opt/start.spring.io/start-client/node_modules/socks/build/client/socksclient.js
[INFO] - /opt/start.spring.io/start-client/node_modules/socks/build/index.js
[INFO] - /opt/start.spring.io/start-client/node_modules/socks-proxy-agent/dist/index.js
[INFO] - /opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/agent.js
[INFO] - /opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/remote.js
[INFO] - /opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/cache/entry.js
[INFO] - /opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/cache/index.js
[INFO] - /opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/fetch.js
[INFO] - /opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/index.js
[INFO] - /opt/start.spring.io/start-client/node_modules/node-sass/scripts/install.js
[INFO]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
[INFO]     at Function.Module._load (node:internal/modules/cjs/loader:871:27)
[INFO]     at Module.require (node:internal/modules/cjs/loader:1098:19)
[INFO]     at require (node:internal/modules/cjs/helpers:108:18)
[INFO]     at Object.<anonymous> (/opt/start.spring.io/start-client/node_modules/socks/build/client/socksclient.js:17:21)
[INFO]     at Module._compile (node:internal/modules/cjs/loader:1196:14)
[INFO]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
[INFO]     at Module.load (node:internal/modules/cjs/loader:1074:32)
[INFO]     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[INFO]     at Module.require (node:internal/modules/cjs/loader:1098:19) {
[INFO]   code: 'MODULE_NOT_FOUND',
[INFO]   requireStack: [
[INFO]     '/opt/start.spring.io/start-client/node_modules/socks/build/client/socksclient.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/socks/build/index.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/socks-proxy-agent/dist/index.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/agent.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/remote.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/cache/entry.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/cache/index.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/fetch.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/make-fetch-happen/lib/index.js',
[INFO]     '/opt/start.spring.io/start-client/node_modules/node-sass/scripts/install.js'
[INFO]   ]
[INFO] }
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for start.spring.io 0.0.1-SNAPSHOT:
[INFO] 
[INFO] start.spring.io .................................... SUCCESS [  0.704 s]
[INFO] start.spring.io client ............................. FAILURE [  9.846 s]
[INFO] start.spring.io website ............................ SKIPPED
[INFO] start.spring.io website verification ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.121 s
[INFO] Finished at: 2023-11-15T01:08:33-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.13.4:yarn (yarn install) on project start-client: Failed to run task: 'yarn ' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :start-client

**Comment by snicoll** [comment]
Alright, closing this one due to the lack of feedback. We can reopen if the repo is updated as requested.
