### ISSUE TITLE
Error with Spring Contract Verifier, Kotlin and Gradle

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/start.spring.io#273]
When creating a new project with Spring Contract Verifier, Kotlin and Gradle, an error happens on server side and no archive is generated.

**Comment by snicoll** [comment]
The extension is adding something to the `buildscript` which is not supported by the Kotlin DSL. Here's the stacktrace:

```
java.lang.IllegalStateException: build.gradle.kts scripts shouldn't need a buildscript
	at io.spring.initializr.generator.buildsystem.gradle.KotlinDslGradleBuildWriter.writeBuildscript(KotlinDslGradleBuildWriter.java:60) ~[classes/:na]
	at io.spring.initializr.generator.buildsystem.gradle.GradleBuildWriter.writeTo(GradleBuildWriter.java:58) ~[classes/:na]
	at io.spring.initializr.generator.spring.build.gradle.GradleBuildProjectContributor.writeBuild(GradleBuildProjectContributor.java:64) ~[classes/:na]
	at io.spring.initializr.generator.spring.build.gradle.GradleBuildProjectContributor.contribute(GradleBuildProjectContributor.java:58) ~[classes/:na]
	at io.spring.initializr.generator.project.DefaultProjectAssetGenerator.generate(DefaultProjectAssetGenerator.java:63) ~[classes/:na]
	at io.spring.initializr.web.project.ProjectGenerationInvoker.lambda$generateProject$1(ProjectGenerationInvoker.java:97) ~[classes/:na]
	at io.spring.initializr.generator.project.ProjectGenerator.generate(ProjectGenerator.java:66) ~[classes/:na]
	at io.spring.initializr.web.project.ProjectGenerationInvoker.invokeProjectStructureGeneration(ProjectGenerationInvoker.java:85) ~[classes/:na]
	at io.spring.initializr.web.controller.ProjectGenerationController.springZip(ProjectGenerationController.java:131) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
```

**Comment by snicoll** [comment]
I've disabled Spring Cloud contract with Kotlin for the time being to avoid the error (see 
53fa93e). We'll use this issue to move to the new plugin DSL across the board.
