### ISSUE TITLE
Verification tests are failing on Java 11

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#484]
When running verification tests on Java 11, they fail with the following:

```
[ERROR] dependencyStarterConfigurationIsCorrect{Dependency, List, List, String}[618]  Time elapsed: 0.157 s  <<< ERROR!
java.lang.RuntimeException: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.springframework.cloud:spring-cloud-starter-contract-verifier:pom:2.2.3.RELEASE -> io.rest-assured:rest-assured:jar:3.3.0 -> io.rest-assured:xml-path:jar:3.3.0 -> com.sun.xml.bind:jaxb-osgi:jar:2.2.10
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.springframework.cloud:spring-cloud-starter-contract-verifier:pom:2.2.3.RELEASE -> io.rest-assured:rest-assured:jar:3.3.0 -> io.rest-assured:xml-path:jar:3.3.0 -> com.sun.xml.bind:jaxb-osgi:jar:2.2.10
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.springframework.cloud:spring-cloud-starter-contract-verifier:pom:2.2.3.RELEASE -> io.rest-assured:rest-assured:jar:3.3.0 -> io.rest-assured:xml-path:jar:3.3.0 -> com.sun.xml.bind:jaxb-osgi:jar:2.2.10
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.sun.xml.bind:jaxb-osgi:jar:2.2.10
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.apache.maven.model.building.ModelBuildingException:
1 problem was encountered while building the effective model for com.sun.xml.bind:jaxb-osgi:2.2.10
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @

	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
```

Running Maven manually lead to a similar warning as well:

```
[WARNING] The POM for com.sun.xml.bind:jaxb-osgi:jar:2.2.10 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.sun.xml.bind:jaxb-osgi:2.2.10
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ 
```

The offending jar is no longer a transitive dependency of rest assured as of `4.4.1` (see https://github.com/rest-assured/rest-assured/issues/1209). Given that Maven manages to build the project (with the warning), I wonder if we shouldn't have some sort of exclusion for this particular issue for the time being.

**Comment by snicoll** [comment]
I've attempted  to add an exclusion to that faulty artifact when Spring Cloud Contract is selected. I can see that the warning on the command line goes away when building such a project but the metadata verification tests are still failing (it looks like it attempts to build a descriptor for `jaxb-osgi` even though it is excluded.
