### ISSUE TITLE
Generated project with Liquibase producing error

### ISSUE THREAD

**Issue by eeriksp** [spring-io/start.spring.io#535]
I generated a project with the following configuration:

![image](https://user-images.githubusercontent.com/35540617/93531901-a4703500-f948-11ea-82a3-ad4e8b4e5945.png)

After importing the project and running it with InteliJ, I got an error declaring that the file `resources/db.changelog/db.changelog-master.yaml` was not found.

I propose that the file should be generated automatically so that it would be possible to get the generated project running without further configuration.

**Comment by snicoll** [comment]
Thanks for the suggestion. We already create the directory structure for you automatically (see #165). Liquibase has many ways of declaring how the changelog can be structured and YAML is just one of them. By creating that file we would have an opinion and we don't have one.

Besides, creating an empty file as you suggest leads to:

```
Caused by: liquibase.exception.ChangeLogParseException: Empty file classpath:/db/changelog/db.changelog-master.yaml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:34) ~[liquibase-core-3.8.9.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217) ~[liquibase-core-3.8.9.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:190) ~[liquibase-core-3.8.9.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.8.9.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366) ~[liquibase-core-3.8.9.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314) ~[liquibase-core-3.8.9.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 18 common frames omitted

```

The current message is much better as it indicates you that a changelog is necessary. If you want to use Liquibase, their documentation should help you to complete the setup of your project. It's perfectly normal for a project generated on start.spring.io to fail if you've included dependencies that require your attention and for which we can't have an opinion. This is one of those cases.

Having said all of that, perhaps we could include a section in `HELP.md` to guide users to what the next steps are. What do you think?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
